# Generated by Django 4.1.3 on 2022-11-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
