# Generated by Django 4.1.2 on 2022-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CO', 'Computers'), ('HA', 'Home Aplliances'), ('MS', 'Mobiles & Smartwatch'), ('S', 'Sound')], max_length=255),
        ),
    ]
