# Generated by Django 4.1.2 on 2022-11-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexiconapp', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
    ]
